production:
  <<: *default
  database: <%= ENV['rds-mysql-server'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['root'] %>
  username: <%= ENV['rds-mysql-server.cx2qpbcrwx0i.ap-northeast-1.rds.amazonaws.com'] %>
  password: <%= ENV['rqUAtx4sMk9m52G'] %>