# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Prefecture.create(:name => '北海道', :kana => 'ホッカイドウ', :hira => 'ほっかいどう')
Prefecture.create(:name => '青森県', :kana => 'アオモリケン', :hira => 'あおもりけん')
Prefecture.create(:name => '岩手県', :kana => 'イワテケン', :hira => 'いわてけん')
Prefecture.create(:name => '宮城県', :kana => 'ミヤギケン', :hira => 'みやざきけん')
Prefecture.create(:name => '秋田県', :kana => 'アキタケン', :hira => 'あきたけん')
Prefecture.create(:name => '山形県', :kana => 'ヤマガタケン', :hira => 'やまがたけん')
Prefecture.create(:name => '福島県', :kana => 'フクシマケン', :hira => 'ふくしまけん')
Prefecture.create(:name => '茨城県', :kana => 'イバラキケン', :hira => 'いばらきけん')
Prefecture.create(:name => '栃木県', :kana => 'トチギケン', :hira => 'とちぎけん')
Prefecture.create(:name => '群馬県', :kana => 'グンマケン', :hira => 'ぐんまけん')
Prefecture.create(:name => '埼玉県', :kana => 'サイタマケン', :hira => 'さいたまけん')
Prefecture.create(:name => '千葉県', :kana => 'チバケン', :hira => 'ちばけん')
Prefecture.create(:name => '東京都', :kana => 'トウキョウト', :hira => 'とうきょうと')
Prefecture.create(:name => '神奈川', :kana => 'カナガワケン', :hira => 'かながわけん')
Prefecture.create(:name => '新潟県', :kana => 'ニイガタケン', :hira => 'にいがたけん')
Prefecture.create(:name => '富山県', :kana => 'トヤマケン', :hira => 'とやまけん')
Prefecture.create(:name => '石川県', :kana => 'イシカワケン', :hira => 'いしかわけん')
Prefecture.create(:name => '福井県', :kana => 'フクイケン', :hira => 'ふくいけん')
Prefecture.create(:name => '山梨県', :kana => 'ヤマナシケン', :hira => 'やまなしけん')
Prefecture.create(:name => '長野県', :kana => 'ナガノケン', :hira => 'ながのけん')
Prefecture.create(:name => '岐阜県', :kana => 'ギフケン', :hira => 'ぎふけん')
Prefecture.create(:name => '静岡県', :kana =>'シズオカケン', :hira => 'しずおかけん')
Prefecture.create(:name => '愛知県', :kana => 'アイチケン', :hira => 'あいちけん')
Prefecture.create(:name => '三重県', :kana => 'ミエケン', :hira => 'みえけん')
Prefecture.create(:name => '滋賀県', :kana => 'シガケン', :hira => 'しがけん')
Prefecture.create(:name => '京都府', :kana => 'キョウトフ', :hira => 'きょうとふ')
Prefecture.create(:name => '大阪府', :kana => 'オオサカフ', :hira => 'おおさかふ')
Prefecture.create(:name => '兵庫県', :kana => 'ヒョウゴケン', :hira => 'ひょうごけん')
Prefecture.create(:name => '奈良県', :kana => 'ナラケン', :hira => 'ならけん')
Prefecture.create(:name => '和歌山県', :kana => 'ワカヤマケン', :hira => 'わかやまけん')
Prefecture.create(:name => '鳥取県', :kana => 'トットリケン', :hira => 'とっとりけん')
Prefecture.create(:name => '島根県', :kana => 'シマネケン', :hira => 'しまねけん')
Prefecture.create(:name => '岡山県', :kana => 'オカヤマケン', :hira => 'おかやまけん')
Prefecture.create(:name => '広島県', :kana => 'ヒロシマケン', :hira => 'ひろしまけん')
Prefecture.create(:name => '山口県', :kana => 'ヤマグチケン', :hira => 'やまぐちけん')
Prefecture.create(:name => '徳島県', :kana => 'トクシマケン', :hira => 'とくしまけん')
Prefecture.create(:name => '香川県', :kana => 'カガワケン', :hira => 'かがわけん')
Prefecture.create(:name => '愛媛県', :kana => 'エヒメケン', :hira => 'えひめけん')
Prefecture.create(:name => '高知県', :kana => 'コウチケン', :hira => 'こうちけん')
Prefecture.create(:name => '福岡県', :kana => 'フクオカケン', :hira => 'ふくおかけん')
Prefecture.create(:name => '佐賀県', :kana => 'サガケン', :hira => 'さがけん')
Prefecture.create(:name => '長崎県', :kana => 'ナガサキケン', :hira => 'ながさきけん')
Prefecture.create(:name => '熊本県', :kana => 'クマモトケン', :hira => 'くまもとけん')
Prefecture.create(:name => '大分県', :kana => 'オオイタケン', :hira => 'おおいたけん')
Prefecture.create(:name => '宮崎県', :kana => 'ミヤザキケン', :hira => 'みやざきけん')
Prefecture.create(:name => '鹿児島県', :kana => 'カゴシマケン', :hira => 'かごしまけん')
Prefecture.create(:name => '沖縄県', :kana => 'オキナワケン', :hira => 'おきなわけん')

